/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Sat Oct 05 15:33:21 2019. */

#include "nrc_msg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Oven_Command_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, Oven_Command, type, type, 0),
    PB_LAST_FIELD
};

const pb_field_t TempProfile_fields[2] = {
    PB_REPEATED_FIXED_COUNT(  1, MESSAGE , FIRST, TempProfile, data, data, &TempProfile_Measure_fields),
    PB_LAST_FIELD
};

const pb_field_t TempProfile_Measure_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, TempProfile_Measure, time, time, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, TempProfile_Measure, temp, time, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(TempProfile, data[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Oven_Command_TempProfile_TempProfile_Measure)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(TempProfile, data[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Oven_Command_TempProfile_TempProfile_Measure)
#endif


/* @@protoc_insertion_point(eof) */
