/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Sat Oct 05 15:33:21 2019. */

#ifndef PB_NRC_MSG_PB_H_INCLUDED
#define PB_NRC_MSG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Oven_Command_Type {
    Oven_Command_Type_START = 0,
    Oven_Command_Type_GET_TEMP_PROFILE = 1,
    Oven_Command_Type_STOP = 2
} Oven_Command_Type;
#define _Oven_Command_Type_MIN Oven_Command_Type_START
#define _Oven_Command_Type_MAX Oven_Command_Type_STOP
#define _Oven_Command_Type_ARRAYSIZE ((Oven_Command_Type)(Oven_Command_Type_STOP+1))

/* Struct definitions */
typedef struct _Oven_Command {
    Oven_Command_Type type;
/* @@protoc_insertion_point(struct:Oven_Command) */
} Oven_Command;

typedef struct _TempProfile_Measure {
    uint32_t time;
    uint32_t temp;
/* @@protoc_insertion_point(struct:TempProfile_Measure) */
} TempProfile_Measure;

typedef struct _TempProfile {
    TempProfile_Measure data[20];
/* @@protoc_insertion_point(struct:TempProfile) */
} TempProfile;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Oven_Command_init_default                {_Oven_Command_Type_MIN}
#define TempProfile_init_default                 {{TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default, TempProfile_Measure_init_default}}
#define TempProfile_Measure_init_default         {0, 0}
#define Oven_Command_init_zero                   {_Oven_Command_Type_MIN}
#define TempProfile_init_zero                    {{TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero, TempProfile_Measure_init_zero}}
#define TempProfile_Measure_init_zero            {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Oven_Command_type_tag                    1
#define TempProfile_Measure_time_tag             1
#define TempProfile_Measure_temp_tag             2
#define TempProfile_data_tag                     1

/* Struct field encoding specification for nanopb */
extern const pb_field_t Oven_Command_fields[2];
extern const pb_field_t TempProfile_fields[2];
extern const pb_field_t TempProfile_Measure_fields[3];

/* Maximum encoded size of messages (where known) */
#define Oven_Command_size                        2
#define TempProfile_size                         280
#define TempProfile_Measure_size                 12

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define NRC_MSG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
