# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nrc_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import importlib.util
spec = importlib.util.spec_from_file_location("nanopb_pb2", "../../nrc_protocol_buffers/nanopb/generator/proto/nanopb_pb2.py")
nanopb__pb2 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(nanopb__pb2)

DESCRIPTOR = _descriptor.FileDescriptor(
  name='nrc_msg.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rnrc_msg.proto\x1a\x0cnanopb.proto\"\x95\x01\n\x0bOvenCommand\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.OvenCommand.Type\x12\n\n\x02id\x18\x02 \x01(\r\x12\x17\n\x08priority\x18\x03 \x01(\rB\x05\x92?\x02\x38\x08\"@\n\x04Type\x12\x14\n\x10GET_TEMP_PROFILE\x10\x00\x12\r\n\tGET_STATE\x10\x01\x12\t\n\x05START\x10\x02\x12\x08\n\x04STOP\x10\x03\"0\n\x0bTempMeasure\x12\x0c\n\x04time\x18\x01 \x01(\r\x12\x13\n\x04temp\x18\x02 \x01(\rB\x05\x92?\x02\x38\x10\"R\n\x0bTempProfile\x12\x1a\n\x0b\x63ountPoints\x18\x01 \x01(\rB\x05\x92?\x02\x38\x08\x12\'\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x0c.TempMeasureB\x0b\x92?\x02\x10\n\x92?\x03\x80\x01\x01\"F\n\x14\x41nsCmdGetTempProfile\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1d\n\x07profile\x18\x02 \x01(\x0b\x32\x0c.TempProfile\"J\n\x0e\x41nsCmdGetState\x12\x19\n\x05state\x18\x01 \x01(\x0e\x32\n.OvenState\x12\x1d\n\x05\x65rror\x18\x02 \x01(\x0e\x32\x0e.OvenErrorType\"1\n\x0b\x41nsCmdStart\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tstartTime\x18\x02 \x01(\r\"/\n\nAnsCmdStop\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08stopTime\x18\x02 \x01(\r\"!\n\x0e\x41nsTempMeasure\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\rFinishProgram\x12\x0f\n\x07success\x18\x01 \x01(\x08*\xc7\x01\n\x07MsgType\x12\r\n\tUNDEFINED\x10\x00\x12\x07\n\x03\x43MD\x10\x01\x12\x1c\n\x18\x41NS_CMD_GET_TEMP_PROFILE\x10\x02\x12\x15\n\x11\x41NS_CMD_GET_STATE\x10\x03\x12\x11\n\rANS_CMD_START\x10\x04\x12\x10\n\x0c\x41NS_CMD_STOP\x10\x05\x12\x10\n\x0cTEMP_MEASURE\x10\x06\x12\x14\n\x10\x41NS_TEMP_MEASURE\x10\x07\x12\x12\n\x0e\x46INISH_PROGRAM\x10\x08\x12\x0e\n\nPLAIN_TEXT\x10\t*&\n\tOvenState\x12\x0b\n\x07STOPPED\x10\x00\x12\x0c\n\x08LAUNCHED\x10\x01*]\n\rOvenErrorType\x12\x08\n\x04NONE\x10\x00\x12\x1d\n\x19\x46\x41ULTY_TEMPERATURE_SENSOR\x10\x01\x12\x10\n\x0c\x46\x41ULTY_RELAY\x10\x02\x12\x11\n\rUNKNOWN_ERROR\x10\x03\x62\x06proto3')
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])

_MSGTYPE = _descriptor.EnumDescriptor(
  name='MsgType',
  full_name='MsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANS_CMD_GET_TEMP_PROFILE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANS_CMD_GET_STATE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANS_CMD_START', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANS_CMD_STOP', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEMP_MEASURE', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANS_TEMP_MEASURE', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISH_PROGRAM', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAIN_TEXT', index=9, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=635,
  serialized_end=834,
)
_sym_db.RegisterEnumDescriptor(_MSGTYPE)

MsgType = enum_type_wrapper.EnumTypeWrapper(_MSGTYPE)
_OVENSTATE = _descriptor.EnumDescriptor(
  name='OvenState',
  full_name='OvenState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAUNCHED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=836,
  serialized_end=874,
)
_sym_db.RegisterEnumDescriptor(_OVENSTATE)

OvenState = enum_type_wrapper.EnumTypeWrapper(_OVENSTATE)
_OVENERRORTYPE = _descriptor.EnumDescriptor(
  name='OvenErrorType',
  full_name='OvenErrorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAULTY_TEMPERATURE_SENSOR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAULTY_RELAY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ERROR', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=876,
  serialized_end=969,
)
_sym_db.RegisterEnumDescriptor(_OVENERRORTYPE)

OvenErrorType = enum_type_wrapper.EnumTypeWrapper(_OVENERRORTYPE)
UNDEFINED = 0
CMD = 1
ANS_CMD_GET_TEMP_PROFILE = 2
ANS_CMD_GET_STATE = 3
ANS_CMD_START = 4
ANS_CMD_STOP = 5
TEMP_MEASURE = 6
ANS_TEMP_MEASURE = 7
FINISH_PROGRAM = 8
PLAIN_TEXT = 9
STOPPED = 0
LAUNCHED = 1
NONE = 0
FAULTY_TEMPERATURE_SENSOR = 1
FAULTY_RELAY = 2
UNKNOWN_ERROR = 3


_OVENCOMMAND_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='OvenCommand.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET_TEMP_PROFILE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_STATE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=117,
  serialized_end=181,
)
_sym_db.RegisterEnumDescriptor(_OVENCOMMAND_TYPE)


_OVENCOMMAND = _descriptor.Descriptor(
  name='OvenCommand',
  full_name='OvenCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='OvenCommand.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='OvenCommand.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='OvenCommand.priority', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\0028\010'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OVENCOMMAND_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=181,
)


_TEMPMEASURE = _descriptor.Descriptor(
  name='TempMeasure',
  full_name='TempMeasure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='TempMeasure.time', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp', full_name='TempMeasure.temp', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\0028\020'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=231,
)


_TEMPPROFILE = _descriptor.Descriptor(
  name='TempProfile',
  full_name='TempProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='countPoints', full_name='TempProfile.countPoints', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\0028\010'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='TempProfile.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\222?\002\020\n\222?\003\200\001\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=315,
)


_ANSCMDGETTEMPPROFILE = _descriptor.Descriptor(
  name='AnsCmdGetTempProfile',
  full_name='AnsCmdGetTempProfile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='AnsCmdGetTempProfile.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile', full_name='AnsCmdGetTempProfile.profile', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=387,
)


_ANSCMDGETSTATE = _descriptor.Descriptor(
  name='AnsCmdGetState',
  full_name='AnsCmdGetState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='AnsCmdGetState.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='AnsCmdGetState.error', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=463,
)


_ANSCMDSTART = _descriptor.Descriptor(
  name='AnsCmdStart',
  full_name='AnsCmdStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='AnsCmdStart.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startTime', full_name='AnsCmdStart.startTime', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=514,
)


_ANSCMDSTOP = _descriptor.Descriptor(
  name='AnsCmdStop',
  full_name='AnsCmdStop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='AnsCmdStop.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stopTime', full_name='AnsCmdStop.stopTime', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=516,
  serialized_end=563,
)


_ANSTEMPMEASURE = _descriptor.Descriptor(
  name='AnsTempMeasure',
  full_name='AnsTempMeasure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='AnsTempMeasure.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=565,
  serialized_end=598,
)


_FINISHPROGRAM = _descriptor.Descriptor(
  name='FinishProgram',
  full_name='FinishProgram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='FinishProgram.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=600,
  serialized_end=632,
)

_OVENCOMMAND.fields_by_name['type'].enum_type = _OVENCOMMAND_TYPE
_OVENCOMMAND_TYPE.containing_type = _OVENCOMMAND
_TEMPPROFILE.fields_by_name['data'].message_type = _TEMPMEASURE
_ANSCMDGETTEMPPROFILE.fields_by_name['profile'].message_type = _TEMPPROFILE
_ANSCMDGETSTATE.fields_by_name['state'].enum_type = _OVENSTATE
_ANSCMDGETSTATE.fields_by_name['error'].enum_type = _OVENERRORTYPE
DESCRIPTOR.message_types_by_name['OvenCommand'] = _OVENCOMMAND
DESCRIPTOR.message_types_by_name['TempMeasure'] = _TEMPMEASURE
DESCRIPTOR.message_types_by_name['TempProfile'] = _TEMPPROFILE
DESCRIPTOR.message_types_by_name['AnsCmdGetTempProfile'] = _ANSCMDGETTEMPPROFILE
DESCRIPTOR.message_types_by_name['AnsCmdGetState'] = _ANSCMDGETSTATE
DESCRIPTOR.message_types_by_name['AnsCmdStart'] = _ANSCMDSTART
DESCRIPTOR.message_types_by_name['AnsCmdStop'] = _ANSCMDSTOP
DESCRIPTOR.message_types_by_name['AnsTempMeasure'] = _ANSTEMPMEASURE
DESCRIPTOR.message_types_by_name['FinishProgram'] = _FINISHPROGRAM
DESCRIPTOR.enum_types_by_name['MsgType'] = _MSGTYPE
DESCRIPTOR.enum_types_by_name['OvenState'] = _OVENSTATE
DESCRIPTOR.enum_types_by_name['OvenErrorType'] = _OVENERRORTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OvenCommand = _reflection.GeneratedProtocolMessageType('OvenCommand', (_message.Message,), dict(
  DESCRIPTOR = _OVENCOMMAND,
  __module__ = 'nrc_msg_pb2'
  # @@protoc_insertion_point(class_scope:OvenCommand)
  ))
_sym_db.RegisterMessage(OvenCommand)

TempMeasure = _reflection.GeneratedProtocolMessageType('TempMeasure', (_message.Message,), dict(
  DESCRIPTOR = _TEMPMEASURE,
  __module__ = 'nrc_msg_pb2'
  # @@protoc_insertion_point(class_scope:TempMeasure)
  ))
_sym_db.RegisterMessage(TempMeasure)

TempProfile = _reflection.GeneratedProtocolMessageType('TempProfile', (_message.Message,), dict(
  DESCRIPTOR = _TEMPPROFILE,
  __module__ = 'nrc_msg_pb2'
  # @@protoc_insertion_point(class_scope:TempProfile)
  ))
_sym_db.RegisterMessage(TempProfile)

AnsCmdGetTempProfile = _reflection.GeneratedProtocolMessageType('AnsCmdGetTempProfile', (_message.Message,), dict(
  DESCRIPTOR = _ANSCMDGETTEMPPROFILE,
  __module__ = 'nrc_msg_pb2'
  # @@protoc_insertion_point(class_scope:AnsCmdGetTempProfile)
  ))
_sym_db.RegisterMessage(AnsCmdGetTempProfile)

AnsCmdGetState = _reflection.GeneratedProtocolMessageType('AnsCmdGetState', (_message.Message,), dict(
  DESCRIPTOR = _ANSCMDGETSTATE,
  __module__ = 'nrc_msg_pb2'
  # @@protoc_insertion_point(class_scope:AnsCmdGetState)
  ))
_sym_db.RegisterMessage(AnsCmdGetState)

AnsCmdStart = _reflection.GeneratedProtocolMessageType('AnsCmdStart', (_message.Message,), dict(
  DESCRIPTOR = _ANSCMDSTART,
  __module__ = 'nrc_msg_pb2'
  # @@protoc_insertion_point(class_scope:AnsCmdStart)
  ))
_sym_db.RegisterMessage(AnsCmdStart)

AnsCmdStop = _reflection.GeneratedProtocolMessageType('AnsCmdStop', (_message.Message,), dict(
  DESCRIPTOR = _ANSCMDSTOP,
  __module__ = 'nrc_msg_pb2'
  # @@protoc_insertion_point(class_scope:AnsCmdStop)
  ))
_sym_db.RegisterMessage(AnsCmdStop)

AnsTempMeasure = _reflection.GeneratedProtocolMessageType('AnsTempMeasure', (_message.Message,), dict(
  DESCRIPTOR = _ANSTEMPMEASURE,
  __module__ = 'nrc_msg_pb2'
  # @@protoc_insertion_point(class_scope:AnsTempMeasure)
  ))
_sym_db.RegisterMessage(AnsTempMeasure)

FinishProgram = _reflection.GeneratedProtocolMessageType('FinishProgram', (_message.Message,), dict(
  DESCRIPTOR = _FINISHPROGRAM,
  __module__ = 'nrc_msg_pb2'
  # @@protoc_insertion_point(class_scope:FinishProgram)
  ))
_sym_db.RegisterMessage(FinishProgram)


_OVENCOMMAND.fields_by_name['priority']._options = None
_TEMPMEASURE.fields_by_name['temp']._options = None
_TEMPPROFILE.fields_by_name['countPoints']._options = None
_TEMPPROFILE.fields_by_name['data']._options = None
# @@protoc_insertion_point(module_scope)
